### ISSUE TITLE
deviceInfo Key not always present on loungeStatus event

### ISSUE THREAD

**Issue by dmunozv04** [FabioGNR/pyytlounge#2]
As the title says, on some devices like the Nintendo Switch, the loungeStatus event seems to not always include the deviceInfo key, causing an error and disconnecting from the events subscription.

The message received (with the key missing): `{'app': 'lb-v4', 'capabilities': 'dsp,mic,dpa,ntb,vsp,que,mus', 'clientName': 'tvhtml5', 'experiments': '', 'name': 'Nintendo Switch', 'theme': 'cl', 'id': 'XXXXXXXXXXXXXXXXXXX', 'type': 'LOUNGE_SCREEN', 'hasCc': 'true', 'receiverIdentityMatchStatus': 'IS_RECEIVER'}
`

The traceback: `Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/pyytlounge/wrapper.py", line 374, in connect
    self.__process_events(events)
  File "/venv/lib/python3.9/site-packages/pyytlounge/wrapper.py", line 290, in __process_events
    self.__process_event(event_id, event_type, args)
  File "/venv/lib/python3.9/site-packages/pyytlounge/wrapper.py", line 271, in __process_event
    self.__device_info = json.loads(device["deviceInfo"])
KeyError: 'deviceInfo'`

If you are fine with it, I'd be willing to make a PR myself to fix this. 
Also, thanks for creating this amazing wrapper for the youtube lounge api

**Comment by FabioGNR** [comment]
Thank you for reporting this issue!
PRs are definitely welcome.
I'll add some form of tests so that other devices like yours hopefully don't break.
