### ISSUE TITLE
Question: building wheels for this package

### ISSUE THREAD

**Issue by dmunozv04** [FabioGNR/pyytlounge#4]
Hi, I was wondering if it would be possible to build wheels for this project, since it would make it much easier when using it as a library and installing it. I could try to make a PR with a GitHub action, if that sounds ok.

**Comment by FabioGNR** [comment]
Yeah, no objections to that. I'm not very familiar with it so a PR would be great :)

**Comment by dmunozv04** [comment]
Great, I'll give it a try though I'm not familiar either

**Comment by dmunozv04** [comment]
It looks like you already build wheels, sorry for making this issue.
It can be seen [here](https://pypi.org/project/pyytlounge/#files)
